// <auto-generated />
using System;
using InstanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstanceService.Data.Migrations
{
    [DbContext(typeof(InstanceServiceDbContext))]
    [Migration("20260616113359_GuidelineOntologyEventIdPk")]
    partial class GuidelineOntologyEventIdPk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("classification_id");

                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("RelationsJson")
                        .HasColumnType("text")
                        .HasColumnName("relations_json");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "ClassificationId")
                        .IsUnique();

                    b.HasIndex("GuidelineVersionId", "Identifier");

                    b.ToTable("guideline_classification", (string)null);
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineClassificationProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentJson")
                        .HasColumnType("text")
                        .HasColumnName("assignment_json");

                    b.Property<string>("ClassificationPropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("classification_property_id");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("default_value");

                    b.Property<Guid>("GuidelineClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_classification_id");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readonly");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertySetId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_set_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<int>("SortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sort_number");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineClassificationId", "ClassificationPropertyId")
                        .IsUnique();

                    b.ToTable("guideline_classification_property", (string)null);
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text")
                        .HasColumnName("extra_json");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("property_type");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("storage_type");

                    b.Property<string>("UnitAbbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_abbreviation");

                    b.Property<string>("UnitType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "PropertyId")
                        .IsUnique();

                    b.ToTable("guideline_property", (string)null);
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelinePropertySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PropertySetId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_set_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "PropertySetId")
                        .IsUnique();

                    b.ToTable("guideline_property_set", (string)null);
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ComplexDataJson")
                        .HasColumnType("text")
                        .HasColumnName("complex_data_json");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DomainJson")
                        .HasColumnType("text")
                        .HasColumnName("domain_json");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("GuidelineId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("guideline_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("MappingsJson")
                        .HasColumnType("text")
                        .HasColumnName("mappings_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .IsDescending();

                    b.HasIndex("ObjectName", "Etag")
                        .IsUnique();

                    b.ToTable("guideline_version", (string)null);
                });

            modelBuilder.Entity("InstanceService.Models.InstanceMetaData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("InstanceMetadata");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyClassHierarchy", b =>
                {
                    b.Property<Guid>("OntologyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChildUri")
                        .HasColumnType("text");

                    b.Property<string>("ParentUri")
                        .HasColumnType("text");

                    b.HasKey("OntologyVersionId", "ChildUri", "ParentUri");

                    b.HasIndex("OntologyVersionId", "ChildUri");

                    b.ToTable("OntologyClassHierarchies");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyRelation", b =>
                {
                    b.Property<Guid>("OntologyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyUri")
                        .HasColumnType("text");

                    b.Property<string>("DomainUri")
                        .HasColumnType("text");

                    b.Property<string>("RangeUri")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OntologyVersionId", "PropertyUri", "DomainUri", "RangeUri");

                    b.HasIndex("OntologyVersionId", "DomainUri");

                    b.HasIndex("OntologyVersionId", "RangeUri");

                    b.ToTable("OntologyRelations");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OntologyVersions");
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineClassification", b =>
                {
                    b.HasOne("InstanceService.Models.Guideline.GuidelineVersion", "GuidelineVersion")
                        .WithMany("Classifications")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineClassificationProperty", b =>
                {
                    b.HasOne("InstanceService.Models.Guideline.GuidelineClassification", "GuidelineClassification")
                        .WithMany("ClassificationProperties")
                        .HasForeignKey("GuidelineClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineClassification");
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineProperty", b =>
                {
                    b.HasOne("InstanceService.Models.Guideline.GuidelineVersion", "GuidelineVersion")
                        .WithMany("Properties")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelinePropertySet", b =>
                {
                    b.HasOne("InstanceService.Models.Guideline.GuidelineVersion", "GuidelineVersion")
                        .WithMany("PropertySets")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyClassHierarchy", b =>
                {
                    b.HasOne("InstanceService.Models.Ontology.OntologyVersion", null)
                        .WithMany()
                        .HasForeignKey("OntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyRelation", b =>
                {
                    b.HasOne("InstanceService.Models.Ontology.OntologyVersion", null)
                        .WithMany()
                        .HasForeignKey("OntologyVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineClassification", b =>
                {
                    b.Navigation("ClassificationProperties");
                });

            modelBuilder.Entity("InstanceService.Models.Guideline.GuidelineVersion", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Properties");

                    b.Navigation("PropertySets");
                });
#pragma warning restore 612, 618
        }
    }
}
