// <auto-generated />
using System;
using InstanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstanceService.Data.Migrations
{
    [DbContext(typeof(InstanceServiceDbContext))]
    [Migration("20260612071740_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstanceService.Models.InstanceMetaData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("InstanceMetadata");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyClassHierarchy", b =>
                {
                    b.Property<Guid>("OntologyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChildUri")
                        .HasColumnType("text");

                    b.Property<string>("ParentUri")
                        .HasColumnType("text");

                    b.HasKey("OntologyVersionId", "ChildUri", "ParentUri");

                    b.HasIndex("OntologyVersionId", "ChildUri");

                    b.ToTable("OntologyClassHierarchies");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyRelation", b =>
                {
                    b.Property<Guid>("OntologyVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyUri")
                        .HasColumnType("text");

                    b.Property<string>("DomainUri")
                        .HasColumnType("text");

                    b.Property<string>("RangeUri")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OntologyVersionId", "PropertyUri", "DomainUri", "RangeUri");

                    b.HasIndex("OntologyVersionId", "DomainUri");

                    b.HasIndex("OntologyVersionId", "RangeUri");

                    b.ToTable("OntologyRelations");
                });

            modelBuilder.Entity("InstanceService.Models.Ontology.OntologyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OntologyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OntologyId", "Etag")
                        .IsUnique();

                    b.ToTable("OntologyVersions");
                });

            modelBuilder.Entity("InstanceService.Models.UseCaseGuidelineReference", b =>
                {
                    b.Property<string>("UseCaseId")
                        .HasColumnType("text");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UseCaseId");

                    b.ToTable("UseCaseGuidelineReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
